/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package FORMULARIOS;
import CONEXION.CONEXION;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;


/**
 *
 * @author CARLOS
 */
public class LOGIN extends javax.swing.JFrame {
    CONEXION mysql = new CONEXION();
    Connection con = (Connection) mysql.Conectar();
    ResultSet rs=null;
    Statement st = null;
    PreparedStatement pst=null;
    /**
     * Creates new form LOGIN
     */
    public LOGIN() {
        initComponents();
        txtUsuario.requestFocus();
        this.setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        btnSalir = new javax.swing.JButton();
        btnIngresar = new javax.swing.JButton();
        txtUsuario = new javax.swing.JTextField();
        psfContraseña = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        labelTask1 = new org.edisoncor.gui.label.LabelTask();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LOGIN");
        setResizable(false);

        btnSalir.setBackground(new java.awt.Color(255, 0, 0));
        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/LOGOUT.png"))); // NOI18N
        btnSalir.setToolTipText("SALIR");
        btnSalir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        btnSalir.setBounds(350, 270, 90, 90);
        jDesktopPane1.add(btnSalir, javax.swing.JLayeredPane.DEFAULT_LAYER);

        btnIngresar.setBackground(new java.awt.Color(51, 102, 0));
        btnIngresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/LOGIN.png"))); // NOI18N
        btnIngresar.setToolTipText("INGRESAR");
        btnIngresar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });
        btnIngresar.setBounds(250, 270, 90, 90);
        jDesktopPane1.add(btnIngresar, javax.swing.JLayeredPane.DEFAULT_LAYER);

        txtUsuario.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtUsuario.setForeground(new java.awt.Color(0, 51, 204));
        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });
        txtUsuario.setBounds(260, 180, 170, 30);
        jDesktopPane1.add(txtUsuario, javax.swing.JLayeredPane.DEFAULT_LAYER);

        psfContraseña.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        psfContraseña.setForeground(new java.awt.Color(0, 51, 204));
        psfContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                psfContraseñaActionPerformed(evt);
            }
        });
        psfContraseña.setBounds(260, 220, 170, 30);
        jDesktopPane1.add(psfContraseña, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("CONTRASEÑA");
        jLabel3.setToolTipText("");
        jLabel3.setBounds(100, 220, 150, 30);
        jDesktopPane1.add(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("USAURIO");
        jLabel4.setToolTipText("");
        jLabel4.setBounds(100, 180, 90, 30);
        jDesktopPane1.add(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        labelTask1.setForeground(new java.awt.Color(255, 255, 255));
        labelTask1.setText("INFORMACIÓN");
        labelTask1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelTask1MouseClicked(evt);
            }
        });
        labelTask1.setBounds(10, 360, 220, 50);
        jDesktopPane1.add(labelTask1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/fond.jpg"))); // NOI18N
        jLabel1.setBounds(0, 150, 540, 280);
        jDesktopPane1.add(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/mp.JPG"))); // NOI18N
        jLabel2.setBounds(0, 0, 541, 160);
        jDesktopPane1.add(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 533, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 428, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        PRINCIPAL pri = new PRINCIPAL();        
        String sql="select usuario, contraseña from usuarios where usuario=? and contraseña=?";
        String pass=String.valueOf(psfContraseña.getPassword());
        String usuario=txtUsuario.getText();
        String dni = null;
        String estado = null;
        String idtipo = null;
        String iddep = null;
        String nombDep = null;
        String personal = null;
        
        try {
                pst=con.prepareStatement(sql);
                pst.setString(1, usuario);
                pst.setString(2, pass);
                rs=pst.executeQuery();
                if(rs.next()){
                    String sql2="select dni,idtipo_usuario, estado from usuarios where usuario='"+usuario+"' and contraseña='"+pass+"'";
                    try {
                        st = con.createStatement();
                        rs=st.executeQuery(sql2);
                        while(rs.next()){
                            dni=rs.getString(1);
                            idtipo=rs.getString(2);
                            estado=rs.getString(3);
                        }
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, e);
                    }
                    String sSQL="select iddependencia, concat(NOMBRES,' ',APELLIDOS)as personal from personal where dni="+dni;
                    try {
                        st = con.createStatement();
                        rs = st.executeQuery(sSQL);
                        while(rs.next()){
                            iddep=rs.getString(1);
                            personal=rs.getString(2);
                        }
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, e);
                    }
                    String sSQL3="select dependencia from dependencias where iddependencia="+iddep;
                    try {
                        st = con.createStatement();
                        rs = st.executeQuery(sSQL3);
                        while(rs.next()){
                            nombDep=rs.getString(1);
                        }
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, e);
                    }
                }
                else{
                    JOptionPane.showMessageDialog(null, "EL USUARIO Y/O LA "
                            + "CONTRASEÑA \n *** SON INCORRECTOS ***");
                }
        } catch (SQLException | HeadlessException e) {
            JOptionPane.showMessageDialog(null, e);
        }
        if("2".equals(iddep) && "ACTIVO".equals(estado) && "2".equals(idtipo)) {
            try {
                pst=con.prepareStatement(sql);
                pst.setString(1, usuario);
                pst.setString(2, pass);
                rs=pst.executeQuery();
                if(rs.next()){
                    JOptionPane.showMessageDialog(null, "BIENVENIDO");
                    pri.Administrador(false);
                    pri.Administracion(true);
                    pri.setUsuario(usuario);
                    pri.setDependencia(iddep);
                    pri.lblDepen.setText(nombDep);
                    pri.lblNomApe.setText(personal);
                    pri.setVisible(true);
                    this.dispose();
                }
                else{
                    JOptionPane.showMessageDialog(null, "EL USUARIO Y/O LA "
                            + "CONTRASEÑA \n *** SON INCORRECTOS ***");
                }
            } catch (SQLException | HeadlessException e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }
       else if("11".equals(iddep) && "ACTIVO".equals(estado) && "2".equals(idtipo)) {
            try {
                pst=con.prepareStatement(sql);
                pst.setString(1, usuario);
                pst.setString(2, pass);
                rs=pst.executeQuery();
                if(rs.next()){
                    JOptionPane.showMessageDialog(null, "BIENVENIDO");
                    pri.Administrador(false);
                    pri.AtenUsua(true);
                    pri.setUsuario(usuario);
                    pri.setDependencia(iddep);
                    pri.lblDepen.setText(nombDep);
                    pri.lblNomApe.setText(personal);
                    pri.setVisible(true);
                    this.dispose();
                }
                else{
                    JOptionPane.showMessageDialog(null, "EL USUARIO Y/O LA "
                            + "CONTRASEÑA \n *** SON INCORRECTOS ***");
                }
            } catch (SQLException | HeadlessException e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }
       else if("1".equals(idtipo) && "ACTIVO".equals(estado)){
           try {
                pst=con.prepareStatement(sql);
                pst.setString(1, usuario);
                pst.setString(2, pass);
                rs=pst.executeQuery();
                if(rs.next()){
                    JOptionPane.showMessageDialog(null, "BIENVENIDO ADMINISTRADOR ");
                    pri.Administrador(true);
                    pri.setUsuario(usuario);
                    pri.setDependencia(iddep);
                    pri.lblDepen.setText(nombDep);
                    pri.lblNomApe.setText(personal);
                    pri.setVisible(true);
                    this.dispose();
                }
                else{
                    JOptionPane.showMessageDialog(null, "EL USUARIO Y/O LA "
                            + "CONTRASEÑA \n *** SON INCORRECTOS ***");
                }
            } catch (SQLException | HeadlessException e) {
                JOptionPane.showMessageDialog(null, e);
            }
       }      
       else if("3".equals(idtipo)&& "ACTIVO".equals(estado) ){
           try {
               pst=con.prepareStatement(sql);
               pst.setString(1, usuario);
               pst.setString(2, pass);
               rs=pst.executeQuery();
               if(rs.next()){
                   JOptionPane.showMessageDialog(null, "BIENVENIDO");
                   pri.Administrador(false);
                   pri.Otros(true);
                   pri.setUsuario(usuario);
                   pri.setDependencia(iddep);
                   pri.lblDepen.setText(nombDep);
                   pri.lblNomApe.setText(personal);
                   pri.setVisible(true);
                   this.dispose();
               }
           } catch (SQLException | HeadlessException e) {
               JOptionPane.showMessageDialog(null, e);
           } 
       }
       else if("4".equals(idtipo)&& "ACTIVO".equals(estado) ){
           try {
               pst=con.prepareStatement(sql);
               pst.setString(1, usuario);
               pst.setString(2, pass);
               rs=pst.executeQuery();
               if(rs.next()){
                   JOptionPane.showMessageDialog(null, "BIENVENIDO");
                   pri.Administrador(false);
                   pri.Noti1(true);
                   pri.setUsuario(usuario);
                   pri.setDependencia(iddep);
                   pri.lblDepen.setText(nombDep);
                   pri.lblNomApe.setText(personal);
                   pri.setVisible(true);
                   this.dispose();
               }
           } catch (SQLException | HeadlessException e) {
               JOptionPane.showMessageDialog(null, e);
           } 
       }
       else if("5".equals(idtipo)&& "ACTIVO".equals(estado) ){
           try {
               pst=con.prepareStatement(sql);
               pst.setString(1, usuario);
               pst.setString(2, pass);
               rs=pst.executeQuery();
               if(rs.next()){
                   JOptionPane.showMessageDialog(null, "BIENVENIDO");
                   pri.Administrador(false);
                   pri.Noti2(true);
                   pri.setUsuario(usuario);
                   pri.setDependencia(iddep);
                   pri.lblDepen.setText(nombDep);
                   pri.lblNomApe.setText(personal);
                   pri.setVisible(true);
                   this.dispose();
               }
           } catch (SQLException | HeadlessException e) {
               JOptionPane.showMessageDialog(null, e);
           } 
       }
       else if ("INACTIVO".equals(estado)) {
           JOptionPane.showMessageDialog(rootPane, "SU CUENTA HA SIDO BLOQUEADA O ELIMINADA "
                   + "\n PARA MAYOR INFORMACIÓN DEBE CONTACTARCE CON EL ADMINISTRADOR");
       }
    }//GEN-LAST:event_btnIngresarActionPerformed

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        txtUsuario.transferFocus();
    }//GEN-LAST:event_txtUsuarioActionPerformed

    private void psfContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_psfContraseñaActionPerformed
        psfContraseña.transferFocus();
    }//GEN-LAST:event_psfContraseñaActionPerformed

    private void labelTask1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelTask1MouseClicked
        INFORMACION info = new INFORMACION(this, true);
        info.setVisible(true);
    }//GEN-LAST:event_labelTask1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LOGIN().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIngresar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private org.edisoncor.gui.label.LabelTask labelTask1;
    private javax.swing.JPasswordField psfContraseña;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
