/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package FORMULARIOS;

/**
 *
 * @author CARLOS
 */
public class PRINCIPAL extends javax.swing.JFrame {

    /**
     * Creates new form PRINCIPAL
     */
    public PRINCIPAL() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    public void Administrador(boolean a){
        btnAdmin.setEnabled(a);
        btnAtender.setEnabled(a);
        btnConsultas.setEnabled(a);
        btnDerivar.setEnabled(a);
        btnEmitidos.setEnabled(a);
        btnRecepcion.setEnabled(a);
        btnRegistro.setEnabled(a);
        btnSalir.setEnabled(a);
        btntGuias.setEnabled(a);
        btnAdmin.setVisible(true);
        btnReportes.setVisible(true);
    }
    public void Administracion(boolean a){
        btnAtender.setEnabled(a);
        btnConsultas.setEnabled(a);
        btnDerivar.setEnabled(a);
        btnEmitidos.setEnabled(a);
        btnRecepcion.setEnabled(a);
        btnRegistro.setEnabled(a);
        btnSalir.setEnabled(a);
        btntGuias.setEnabled(a);
        btnAdmin.setVisible(false);
        btnReportes.setVisible(false);
        btnAsignar.setVisible(false);
        btnReportes.setVisible(false);
        btnRecepcionNoti.setVisible(false);
    }
    public void AtenUsua(boolean a ){
        btnAtender.setEnabled(a);
        btnConsultas.setEnabled(a);
        btnDerivar.setEnabled(a);
        btnRecepcion.setEnabled(a);
        btnRegistro.setEnabled(a);
        btnSalir.setEnabled(a);
        btnAdmin.setVisible(false);
        btntGuias.setVisible(false);
        btnEmitidos.setVisible(false);
        btnReportes.setVisible(false);
        btnAsignar.setVisible(false);
        btnReportes.setVisible(false);
        btnRecepcionNoti.setVisible(false);
    }
    public void Otros(boolean a){
        btnAtender.setEnabled(a);
        btnConsultas.setEnabled(a);
        btnDerivar.setEnabled(a);
        btnRecepcion.setEnabled(a);
        btnRegistro.setEnabled(a);
        btnSalir.setEnabled(a);
        btnAdmin.setVisible(false);
        btntGuias.setVisible(false);
        btnEmitidos.setVisible(false);
        btnReportes.setVisible(false);
        btnAsignar.setVisible(false);
        btnReportes.setVisible(false);
        btnRecepcionNoti.setVisible(false);
    }
    public void Noti1(boolean a){
        btnAtender.setEnabled(a);
        btnConsultas.setEnabled(a);
        btnAsignar.setEnabled(a);
        btnRecepcion.setEnabled(a);
        btnRegistro.setEnabled(a);
        btnSalir.setEnabled(a);
        btnAdmin.setVisible(false);
        btntGuias.setVisible(false);
        btnEmitidos.setVisible(false);
        btnReportes.setVisible(a);
        btnDerivar.setVisible(false);
        btnRecepcionNoti.setVisible(false);
    }
    public void Noti2(boolean a){
        btnAtender.setEnabled(a);
        btnRecepcionNoti.setEnabled(a);
        btnSalir.setEnabled(a);
        btnAdmin.setVisible(false);
        btntGuias.setVisible(false);
        btnEmitidos.setVisible(false);
        btnReportes.setVisible(false);
        btnDerivar.setVisible(false);
        btnAsignar.setEnabled(false);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new org.edisoncor.gui.panel.Panel();
        panelShadow1 = new org.edisoncor.gui.panel.PanelShadow();
        jLabel1 = new javax.swing.JLabel();
        lblNomApe = new javax.swing.JLabel();
        lblDepen = new javax.swing.JLabel();
        panelCurves1 = new org.edisoncor.gui.panel.PanelCurves();
        jToolBar1 = new javax.swing.JToolBar();
        btnAdmin = new javax.swing.JButton();
        btnRegistro = new javax.swing.JButton();
        btnDerivar = new javax.swing.JButton();
        btnRecepcion = new javax.swing.JButton();
        btnAtender = new javax.swing.JButton();
        btntGuias = new javax.swing.JButton();
        btnEmitidos = new javax.swing.JButton();
        btnConsultas = new javax.swing.JButton();
        btnAsignar = new javax.swing.JButton();
        btnRecepcionNoti = new javax.swing.JButton();
        btnReportes = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PRINCIPAL");

        panel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/MINISTRIO.JPG"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 255));
        jLabel1.setText("BIENVENIDO");

        lblNomApe.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        lblNomApe.setForeground(new java.awt.Color(102, 204, 0));

        lblDepen.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        lblDepen.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout panelShadow1Layout = new javax.swing.GroupLayout(panelShadow1);
        panelShadow1.setLayout(panelShadow1Layout);
        panelShadow1Layout.setHorizontalGroup(
            panelShadow1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelShadow1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelShadow1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblDepen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelShadow1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblNomApe, javax.swing.GroupLayout.DEFAULT_SIZE, 625, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelShadow1Layout.setVerticalGroup(
            panelShadow1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelShadow1Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(panelShadow1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblNomApe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblDepen, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addComponent(panelShadow1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(panelCurves1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addComponent(panelCurves1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 235, Short.MAX_VALUE)
                .addComponent(panelShadow1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jToolBar1.setBackground(new java.awt.Color(255, 255, 255));
        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        btnAdmin.setBackground(new java.awt.Color(255, 255, 255));
        btnAdmin.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/admin.png"))); // NOI18N
        btnAdmin.setText("ADMINISTRAR");
        btnAdmin.setToolTipText("ADMINISTRADOR DEL SISTEMA");
        btnAdmin.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnAdmin.setFocusable(false);
        btnAdmin.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAdmin.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminActionPerformed(evt);
            }
        });
        jToolBar1.add(btnAdmin);

        btnRegistro.setBackground(new java.awt.Color(255, 255, 255));
        btnRegistro.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnRegistro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/REGISTRO.png"))); // NOI18N
        btnRegistro.setText("REGISTRAR");
        btnRegistro.setToolTipText("REGISTRO DE DOCUMENTOS");
        btnRegistro.setFocusable(false);
        btnRegistro.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRegistro.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistroActionPerformed(evt);
            }
        });
        jToolBar1.add(btnRegistro);

        btnDerivar.setBackground(new java.awt.Color(255, 255, 255));
        btnDerivar.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnDerivar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/DERIVAR.png"))); // NOI18N
        btnDerivar.setText("DERIVAR");
        btnDerivar.setToolTipText("DEFVIAR DOCUEMTOS");
        btnDerivar.setFocusable(false);
        btnDerivar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDerivar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnDerivar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDerivarActionPerformed(evt);
            }
        });
        jToolBar1.add(btnDerivar);

        btnRecepcion.setBackground(new java.awt.Color(255, 255, 255));
        btnRecepcion.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnRecepcion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/recepcion.png"))); // NOI18N
        btnRecepcion.setText("RECEPCIÓN");
        btnRecepcion.setToolTipText("RECEPCION DE DOCUMENTOS");
        btnRecepcion.setFocusable(false);
        btnRecepcion.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRecepcion.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnRecepcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecepcionActionPerformed(evt);
            }
        });
        jToolBar1.add(btnRecepcion);

        btnAtender.setBackground(new java.awt.Color(255, 255, 255));
        btnAtender.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnAtender.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/doc1.png"))); // NOI18N
        btnAtender.setText("ATENDER");
        btnAtender.setToolTipText("ATENDER DOCUMENTOS");
        btnAtender.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnAtender.setFocusable(false);
        btnAtender.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAtender.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAtender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtenderActionPerformed(evt);
            }
        });
        jToolBar1.add(btnAtender);

        btntGuias.setBackground(new java.awt.Color(255, 255, 255));
        btntGuias.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btntGuias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/docs.png"))); // NOI18N
        btntGuias.setText("GUIAS");
        btntGuias.setToolTipText("REGISTRO DE GUIAS");
        btntGuias.setFocusable(false);
        btntGuias.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btntGuias.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btntGuias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntGuiasActionPerformed(evt);
            }
        });
        jToolBar1.add(btntGuias);

        btnEmitidos.setBackground(new java.awt.Color(255, 255, 255));
        btnEmitidos.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnEmitidos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/GIUAS.png"))); // NOI18N
        btnEmitidos.setText("EMITIDOS");
        btnEmitidos.setToolTipText("REGISTRO DE DOCUMENTOS EMITIDOS");
        btnEmitidos.setFocusable(false);
        btnEmitidos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEmitidos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEmitidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmitidosActionPerformed(evt);
            }
        });
        jToolBar1.add(btnEmitidos);

        btnConsultas.setBackground(new java.awt.Color(255, 255, 255));
        btnConsultas.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnConsultas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/CONSULTAR.png"))); // NOI18N
        btnConsultas.setText("CONSULTAS");
        btnConsultas.setToolTipText("CONSULTAS");
        btnConsultas.setFocusable(false);
        btnConsultas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnConsultas.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnConsultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultasActionPerformed(evt);
            }
        });
        jToolBar1.add(btnConsultas);

        btnAsignar.setBackground(new java.awt.Color(255, 255, 255));
        btnAsignar.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnAsignar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/derivacion.png"))); // NOI18N
        btnAsignar.setText("ASIGNAR");
        btnAsignar.setToolTipText("ASIGNAR");
        btnAsignar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnAsignar.setFocusable(false);
        btnAsignar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAsignar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAsignar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsignarActionPerformed(evt);
            }
        });
        jToolBar1.add(btnAsignar);

        btnRecepcionNoti.setBackground(new java.awt.Color(255, 255, 255));
        btnRecepcionNoti.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnRecepcionNoti.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/recepcion1.png"))); // NOI18N
        btnRecepcionNoti.setText("RECEPCIÓN");
        btnRecepcionNoti.setFocusable(false);
        btnRecepcionNoti.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRecepcionNoti.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnRecepcionNoti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecepcionNotiActionPerformed(evt);
            }
        });
        jToolBar1.add(btnRecepcionNoti);

        btnReportes.setBackground(new java.awt.Color(255, 255, 255));
        btnReportes.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnReportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/GRAFICO.png"))); // NOI18N
        btnReportes.setText("REPORTES");
        btnReportes.setFocusable(false);
        btnReportes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnReportes.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btnReportes);

        btnSalir.setBackground(new java.awt.Color(255, 255, 255));
        btnSalir.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(255, 0, 0));
        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/salir.png"))); // NOI18N
        btnSalir.setText("SALIR");
        btnSalir.setFocusable(false);
        btnSalir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSalir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jToolBar1.add(btnSalir);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminActionPerformed
        new LOADER(this, true).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAdminActionPerformed

    private void btnRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistroActionPerformed
        REGISTRAR r = new REGISTRAR(this, true);
        r.setUsuario(this.getUsuario());
        r.setDependencia(this.getDependencia());
        r.setVisible(true);
    }//GEN-LAST:event_btnRegistroActionPerformed

    private void btnDerivarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDerivarActionPerformed
        DERIVAR dr = new DERIVAR();
        dr.setUsuario(this.getUsuario());
        dr.setDependencia(this.getDependencia());
        dr.setVisible(true);
    }//GEN-LAST:event_btnDerivarActionPerformed

    private void btnRecepcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecepcionActionPerformed
        RECEPCION rec = new RECEPCION(this, true);
        rec.Usuario=this.getUsuario();
        rec.Dependencia=this.getDependencia();
        rec.setVisible(true);
    }//GEN-LAST:event_btnRecepcionActionPerformed

    private void btnAtenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtenderActionPerformed
        ATENDER at = new ATENDER(this, true);
        at.setUsuario(this.getUsuario());
        at.setDependencia(this.getDependencia());
        at.setVisible(true);
    }//GEN-LAST:event_btnAtenderActionPerformed

    private void btntGuiasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntGuiasActionPerformed
        new GUIAS(this, true).setVisible(true);
    }//GEN-LAST:event_btntGuiasActionPerformed

    private void btnEmitidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmitidosActionPerformed
        EMITIDOS emi = new EMITIDOS(this, true);
        emi.setUsuario(this.getUsuario());
        emi.setVisible(true);
    }//GEN-LAST:event_btnEmitidosActionPerformed

    private void btnConsultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultasActionPerformed
        CONUSLTA_DOC cd = new CONUSLTA_DOC(this, true);
        cd.setUsuario(this.getUsuario());
        cd.setDependencia(this.getDependencia());
        cd.setVisible(true);
    }//GEN-LAST:event_btnConsultasActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
         System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnAsignarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsignarActionPerformed
        ASIGNAR as = new ASIGNAR();
        as.setDependencia(this.getDependencia());
        as.setUsuario(this.getUsuario());
        as.Combo();
        as.setVisible(true);
    }//GEN-LAST:event_btnAsignarActionPerformed

    private void btnRecepcionNotiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecepcionNotiActionPerformed
        RECIBIR rec = new RECIBIR(this, true);
        rec.setDependencia(this.getDependencia());
        rec.setUsuario(this.getUsuario());
        rec.setNombres(lblNomApe.getText());
        rec.setVisible(true);
    }//GEN-LAST:event_btnRecepcionNotiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PRINCIPAL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new PRINCIPAL().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdmin;
    private javax.swing.JButton btnAsignar;
    private javax.swing.JButton btnAtender;
    private javax.swing.JButton btnConsultas;
    private javax.swing.JButton btnDerivar;
    private javax.swing.JButton btnEmitidos;
    private javax.swing.JButton btnRecepcion;
    private javax.swing.JButton btnRecepcionNoti;
    private javax.swing.JButton btnRegistro;
    private javax.swing.JButton btnReportes;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btntGuias;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JToolBar jToolBar1;
    public javax.swing.JLabel lblDepen;
    public javax.swing.JLabel lblNomApe;
    private org.edisoncor.gui.panel.Panel panel1;
    private org.edisoncor.gui.panel.PanelCurves panelCurves1;
    private org.edisoncor.gui.panel.PanelShadow panelShadow1;
    // End of variables declaration//GEN-END:variables
    String Usuario, Dependencia, NombreApe;

    public String getUsuario() {
        return Usuario;
    }

    public void setUsuario(String Usuario) {
        this.Usuario = Usuario;
    }

    public String getDependencia() {
        return Dependencia;
    }

    public void setDependencia(String Dependencia) {
        this.Dependencia = Dependencia;
    }

    public String getNombreApe() {
        return NombreApe;
    }

    public void setNombreApe(String NombreApe) {
        this.NombreApe = NombreApe;
    }
  
}